
import { Lead, LeadScore, Status, FinancingStatus, LeadSource, FinancialTransactionType, ProjectPhaseStatus } from './types';
import { v4 as uuidv4 } from 'uuid';

const changeOrderDate = new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(); // Set it a few hours in the past

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    address: '123 Maple St, Springfield, IL',
    dossier: {
      ownerName: 'John & Jane Doe',
      estimatedValue: 350000,
      taxLiens: false,
      mortgageDetails: {
        originalLoanAmount: 280000,
        loanYear: 2018,
        lenderName: 'Springfield Bank',
        estimatedRate: 3.8,
        estimatedMonthlyPayment: 1305,
        estimatedRemainingBalance: 245000,
      },
      propertyDetails: {
        yearBuilt: 1995,
        sqFootage: 2200,
        bedrooms: 4,
        bathrooms: 2.5,
        lastSaleDate: '2018-05-15',
        lastSalePrice: 280000,
        lotSize: '0.25 acres',
        yearRenovated: 2020,
        hoaFees: 0,
        propertyType: 'Single-Family',
        roofingMaterial: 'Asphalt Shingle',
        exteriorFinish: 'Vinyl Siding',
        heatingSystem: 'Forced Air',
        coolingSystem: 'Central AC',
      },
      demographics: {
        estHouseholdIncome: '$120k - $140k',
        estOwnerAgeRange: '40-50',
        lifeStageProfile: 'Family with Kids',
        maritalStatus: 'Married',
      },
      projectSuggestions: [
        { name: 'Kitchen Remodel', reason: 'The property was built in 1995; an updated kitchen can significantly increase home value and appeal to the owners\' life stage.', estimatedCost: 30000, estimatedROI: 85 },
        { name: 'Deck or Patio Addition', reason: 'A "Family with Kids" profile suggests a need for outdoor living space for entertainment and relaxation.', estimatedCost: 15000, estimatedROI: 70 },
        { name: 'Master Bathroom Update', reason: 'An updated master bath is a high-ROI project and appeals to homeowners in the 40-50 age range.', estimatedCost: 20000, estimatedROI: 90 }
      ],
      neighborhoodInfo: undefined,
      schoolRatings: undefined,
      recentPermits: undefined,
    },
    leadScore: LeadScore.B,
    leadScoreValue: 50,
    status: Status.Won,
    financingStatus: FinancingStatus.NotOffered,
    estimatedEquity: 105000,
    coords: { lat: 39.7817, lng: -89.6501 },
    activityLog: [
        { id: uuidv4(), timestamp: changeOrderDate, note: 'Change Order #1 created for $2,150.00.' },
        { id: uuidv4(), timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), note: 'Dossier generated via AI Lookup.' }
    ],
    groundingChunks: [],
    quote: undefined,
    source: LeadSource.AI,
    isArchived: false,
    finances: [
        {
            id: uuidv4(),
            type: FinancialTransactionType.Revenue,
            date: changeOrderDate,
            amount: 2150,
            description: 'Change Order #1: Add extra window in master bedroom',
            category: 'Change Order'
        }
    ],
    propertyImage: undefined,
    schedule: {
        id: uuidv4(),
        projectDuration: 'Approx. 5-6 weeks',
        phases: [
            { id: uuidv4(), name: 'Permits and Planning', startDate: '2024-08-01', endDate: '2024-08-10', status: ProjectPhaseStatus.Completed },
            { id: uuidv4(), name: 'Demolition', startDate: '2024-08-11', endDate: '2024-08-13', status: ProjectPhaseStatus.Completed },
            { id: uuidv4(), name: 'Rough-in & Framing', startDate: '2024-08-14', endDate: '2024-08-22', status: ProjectPhaseStatus.InProgress },
            { id: uuidv4(), name: 'Finishing', startDate: '2024-08-23', endDate: '2024-09-05', status: ProjectPhaseStatus.Upcoming },
        ]
    },
    changeOrders: [
       {
        id: uuidv4(),
        createdAt: changeOrderDate,
        description: 'Add extra window in master bedroom',
        scopeOfWork: 'Supply and install one (1) new construction window in the master bedroom. Scope includes framing the new opening, installing the window, insulating, drywall repair, interior trim, and exterior siding/trim repair to match existing conditions. Price does not include painting.',
        lineItems: [
          { id: uuidv4(), description: 'Supply new construction vinyl window (approx. 3x5 ft)', quantity: 1, unitPrice: 750 },
          { id: uuidv4(), description: 'Labor for framing, installation, and finishing', quantity: 12, unitPrice: 75 },
          { id: uuidv4(), description: 'Materials (lumber, insulation, drywall, trim, siding)', quantity: 1, unitPrice: 350 },
          { id: uuidv4(), description: 'Permit Allowance', quantity: 1, unitPrice: 150 }
        ],
        total: 2150
      }
    ],
  },
  {
    id: '4',
    address: '555 Birch Rd, Springfield, IL',
    dossier: {
      ownerName: 'George Banks',
      estimatedValue: 290000,
      taxLiens: false,
      mortgageDetails: {
        originalLoanAmount: 210000,
        loanYear: 2019,
        lenderName: 'First National Bank',
        estimatedRate: 4.1,
        estimatedMonthlyPayment: 1012,
        estimatedRemainingBalance: 190000,
      },
      propertyDetails: {
        yearBuilt: 1998,
        sqFootage: 1800,
        bedrooms: 3,
        bathrooms: 2,
        lastSaleDate: '2019-03-12',
        lastSalePrice: 210000,
        lotSize: undefined,
        yearRenovated: undefined,
        hoaFees: undefined,
        propertyType: undefined,
        roofingMaterial: undefined,
        exteriorFinish: undefined,
        heatingSystem: undefined,
        coolingSystem: undefined,
      },
      demographics: {
        estHouseholdIncome: '$95k - $115k',
        estOwnerAgeRange: '35-45',
        lifeStageProfile: 'Growing Family',
        maritalStatus: 'Married',
      },
       neighborhoodInfo: undefined,
       schoolRatings: undefined,
       recentPermits: undefined,
    },
    leadScore: LeadScore.B,
    leadScoreValue: 45,
    status: Status.New,
    financingStatus: FinancingStatus.NotOffered,
    estimatedEquity: 100000,
    coords: { lat: 39.79, lng: -89.66 },
    activityLog: [
        { id: uuidv4(), timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: 'Lead submitted from "Contact Us" form on website.' }
    ],
    groundingChunks: [],
    quote: undefined,
    source: LeadSource.Web,
    isArchived: false,
    finances: [],
    propertyImage: undefined,
    schedule: undefined,
    changeOrders: [],
  },
  {
    id: '2',
    address: '789 Oak Ave, Shelbyville, IL',
    dossier: {
      ownerName: 'Peter Jones',
      estimatedValue: 220000,
      taxLiens: true,
      mortgageDetails: {
        originalLoanAmount: 200000,
        loanYear: 2021,
        lenderName: 'Shelbyville Credit Union',
        estimatedRate: 4.5,
        estimatedMonthlyPayment: 1013,
        estimatedRemainingBalance: 192000,
      },
      propertyDetails: {
        yearBuilt: 1980,
        sqFootage: 1500,
        bedrooms: 3,
        bathrooms: 2,
        lastSaleDate: '2021-01-20',
        lastSalePrice: 200000,
        lotSize: undefined,
        yearRenovated: undefined,
        hoaFees: undefined,
        propertyType: undefined,
        roofingMaterial: undefined,
        exteriorFinish: undefined,
        heatingSystem: undefined,
        coolingSystem: undefined,
      },
      demographics: {
        estHouseholdIncome: '$70k - $90k',
        estOwnerAgeRange: '30-40',
        lifeStageProfile: 'Single Homeowner',
        maritalStatus: 'Single',
      },
       neighborhoodInfo: undefined,
       schoolRatings: undefined,
       recentPermits: undefined,
    },
    leadScore: LeadScore.C,
    leadScoreValue: 0,
    status: Status.Contacted,
    financingStatus: FinancingStatus.NotOffered,
    estimatedEquity: 28000,
    coords: { lat: 39.4056, lng: -88.7909 },
    activityLog: [
        { id: uuidv4(), timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: 'Called, left voicemail.' },
        { id: uuidv4(), timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), note: 'Manually entered lead from referral.' }
    ],
    groundingChunks: [],
    quote: undefined,
    source: LeadSource.Manual,
    isArchived: true,
    finances: [],
    propertyImage: undefined,
    schedule: undefined,
    changeOrders: [],
  },
  {
    id: '3',
    address: '456 Pine Ln, Capital City, IL',
    dossier: {
      ownerName: 'Mary Smith',
      estimatedValue: 480000,
      taxLiens: false,
      mortgageDetails: {
        originalLoanAmount: 350000,
        loanYear: 2015,
        lenderName: 'Capital City Mortgage Corp',
        estimatedRate: 3.5,
        estimatedMonthlyPayment: 1571,
        estimatedRemainingBalance: 285000,
      },
      propertyDetails: {
        yearBuilt: 2010,
        sqFootage: 3000,
        bedrooms: 5,
        bathrooms: 3.5,
        lastSaleDate: '2015-11-01',
        lastSalePrice: 350000,
        lotSize: '1.2 acres',
        yearRenovated: undefined,
        hoaFees: 250,
        propertyType: undefined,
        roofingMaterial: undefined,
        exteriorFinish: undefined,
        heatingSystem: undefined,
        coolingSystem: undefined,
      },
      demographics: {
        estHouseholdIncome: '$180k - $220k',
        estOwnerAgeRange: '50-60',
        lifeStageProfile: 'Established Family',
        maritalStatus: 'Married',
      },
       neighborhoodInfo: undefined,
       schoolRatings: undefined,
       recentPermits: undefined,
    },
    leadScore: LeadScore.B,
    leadScoreValue: 65,
    status: Status.ProposalSent,
    financingStatus: FinancingStatus.NotOffered,
    estimatedEquity: 195000,
    coords: { lat: 39.8018, lng: -89.6444 },
    activityLog: [
        { id: uuidv4(), timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: 'Sent proposal via email for kitchen remodel.' },
        { id: uuidv4(), timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), note: 'On-site meeting completed. Measured kitchen.' },
        { id: uuidv4(), timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), note: 'Confirmed meeting for Tuesday.' }
    ],
    groundingChunks: [],
    quote: undefined,
    source: LeadSource.AI,
    isArchived: false,
    finances: [
        { id: uuidv4(), type: FinancialTransactionType.Revenue, date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), amount: 5000, description: 'Initial deposit for kitchen remodel.', category: 'Deposit'}
    ],
    propertyImage: undefined,
    schedule: undefined,
    changeOrders: [],
  },
];